import Footer from "@/containers/Footer";
import Navbar from "@/containers/Navbar";
import Link from "next/link";
import React from "react";

const page = () => {
  return (
    <div className="flex min-h-screen flex-col items-center w-full bg-primary-100 ">
      <div className=" bg-primary-500 w-full flex justify-center items-center">
        <div className=" hidden w-9/12 my-16">
          <Link href="/">
            <div className=" flex flex-row cursor-pointer">
              <span>{/* <img src="ep_back.svg" alt="" /> */}</span>
              <span className=" text-white font-bold">{"<-"} Back To Home</span>
            </div>
          </Link>

          <div className=" flex flex-row items-center  my-6">
            <div className=" text-white   font-bold text-4xl">
              Privacy Policy for EnhancifAI
            </div>
          </div>
        </div>
      </div>
      <Navbar />
      <div className=" w-9/12 my-10 text-secondary-500 font-light flex flex-col gap-3 mt-40">
        <div className=" text-4xl font-bold flex justify-center items-center">
          <span className=" text-primary-500 mr-2">Terms of Use </span> For
          EnhancifAI
        </div>
        <div className="  w-4/5 text-center text-lg mx-auto my-4">
          Welcome to EnhancifAI. By accessing or using our platform, you agree
          to be bound by these Terms of Use and our Privacy Policy. If you do
          not agree with any part of these terms, you must not use our services.
        </div>
        <div className="  text-lg mx-auto">
          Eﬀective Date: February 20, 2024
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-20">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Use of Service</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              EnhancifAI provides AI-driven data analysis services, allowing
              users to upload data for processing and analysis. The services are
              intended for business and professional use only.
            </div>
          </div>
        </div>

        <div className="flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>User Responsibilities</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className=" text-lg">
              We use the collected data for various purposes:
            </div>
            <div>
              <ul>
                <li className="  mt-4">
                  <div className="mt-2">
                    Data Accuracy: You are responsible for the accuracy of the
                    data you upload to EnhancifAI.
                  </div>
                </li>
                <li className=" mt-2">
                  <div className="mt-2">
                    Prompt Construction: You must construct clear and precise
                    prompts to guide the AI's analysis. Experimentation with
                    prompt formulations is encouraged to ensure results meet
                    your expectations.
                  </div>
                </li>
                <li className=" mt-2">
                  <div className="mt-2">
                    Data Validation: You are responsible for validating the
                    outputs generated by EnhancifAI for accuracy and
                    applicability to your specific needs.
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Intellectual Property</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              All content provided on EnhancifAI, including text, graphics,
              logos, and software, is the property of EnhancifAI or its content
              suppliers and protected by international copyright laws.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>User Data</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3 gap-4">
            <div className="">
              EnhancifAI acts solely as a conduit for transmitting your data to
              AI services for analysis. We do not use, review, or retain your
              data for any purpose other than to provide the services requested
              by you. Upon completion of the services, any data you have
              uploaded, along with the associated results, are not retained by
              our platform. By uploading data, you grant us a temporary,
              non-exclusive license to transmit, process, and store your data
              solely for performing the requested analysis, without retaining
              your data post-service.
            </div>
            <div className=" text-lg">
              User compliance with Governing Policies
            </div>
            <div>
              You are solely responsible for ensuring that your use of
              EnhancifAI complies with all applicable laws, regulations, and any
              corporate or organizational policies governing the sharing and
              analysis of information. This includes obtaining necessary
              consents and authorizations for sharing data with EnhancifAI and
              for using the generated insights. You agree to indemnify
              EnhancifAI against any claims arising from your failure to comply
              with these obligations.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Data Privacy and Security</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              EnhancifAI is committed to protecting the privacy and security of
              your data. Please refer to our Privacy Policy for detailed
              information on how we collect, use, and protect your data.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Disclaimer of Warranties</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              EnhancifAI is provided "as is " without warranty of any kind,
              express or implied. We strive to provide accurate and reliable
              services but do not guarantee that the services will meet your
              specific requirements or expectations.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Limitation of Liability</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              EnhancifAI or its directors, employees, or agents will not be
              liable for any direct, indirect, incidental, special,
              consequential, or punitive damages resulting from your use of or
              inability to use the service.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Changes to Terms</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              EnhancifAI reserves the right to update or modify these Terms of
              Use at any time without prior notice. Your continued use of the
              service after any changes indicates your acceptance of the new
              Terms.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Governing Law</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              These Terms of Use shall be governed by and construed in
              accordance with the laws of the jurisdiction in which EnhancifAI
              operates, without giving effect to any principles of conflicts of
              law.
            </div>
          </div>
        </div>

        <div className=" flex flex-col md:flex-row w-full gap-8 text-secondary-500 mt-10">
          <div className=" flex flex-row   text-xl  w-full md:w-1/3">
            <div className=" flex flex-row  ">
              <div className=" p-2 ">
                <img src="d_tick_circle.svg" alt="" />
              </div>
              <div>Contacts</div>
            </div>
          </div>
          <div className=" flex flex-col w-2/3">
            <div className="">
              If you have any questions about these Terms of Use, please contact
              us at info@enhancifai.com.
            </div>
          </div>
        </div>

        <div className=" flex italic flex-col  justify-center items-center md:flex-row w-full text-lg gap-8 text-secondary-500 mt-10">
          By using EnhancifAI, you acknowledge that you have read, understood,
          and agree to be bound by these Terms of Use.
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default page;
